name: TIMV
main: com.evilcodes.timv.TIMV
author: EvilCodes
authors: [EvilCodes,evil_dr3am]
version: Alpha-1.0.1
description: An alternative Trouble In Mineville plugin
website: http://www.evilcodes.tk/
commands:
   timv:
      description: Maincommand for some help and more
      usage: /<command> <arg>